from pathlib import Path

path = Path("src/value_dislocation/strategy/rule_learning.py")
text = path.read_text(encoding="utf-8")
old = '''def _attach_forward_returns(analysis: pd.DataFrame, prices: pd.DataFrame) -> pd.DataFrame:\n    if analysis.empty or prices.empty:\n        return pd.DataFrame()\n    frame = analysis.copy()\n    frame["close"] = pd.to_numeric(frame.get("close"), errors="coerce")\n    result_parts: list[pd.DataFrame] = []\n    for code, rows in frame.groupby("code", sort=False):\n        px = prices.loc[prices["code"].astype(str) == str(code), ["date", "close"]]\n        if px.empty:\n            continue\n        dates = px["date"].to_numpy(dtype="datetime64[ns]")\n        closes = px["close"].to_numpy(dtype=float)\n        g = rows.sort_values("analysis_date").copy()\n        entry = pd.to_numeric(g["close"], errors="coerce").to_numpy(dtype=float)\n        base_dates = g["analysis_date"].to_numpy(dtype="datetime64[ns]")\n        for horizon in HORIZONS:\n            target = base_dates + np.timedelta64(horizon, "D")\n            pos = np.searchsorted(dates, target, side="left")\n            values = np.full(len(g), np.nan, dtype=float)\n            valid = (pos < len(dates)) & np.isfinite(entry) & (entry > 0)\n            if valid.any():\n                values[valid] = closes[pos[valid]] / entry[valid] - 1.0\n            g[f"return_{horizon}d"] = values\n        result_parts.append(g)\n    return pd.concat(result_parts, ignore_index=True, sort=False) if result_parts else pd.DataFrame()\n'''
new = '''def _attach_forward_returns(analysis: pd.DataFrame, prices: pd.DataFrame) -> pd.DataFrame:\n    if analysis.empty or prices.empty:\n        return pd.DataFrame()\n    frame = analysis.copy()\n    frame["close"] = pd.to_numeric(frame.get("close"), errors="coerce")\n\n    # Build the price lookup once. The previous implementation filtered the complete\n    # multi-million-row price DataFrame once per security, which becomes effectively\n    # O(securities x price_rows) as history grows and can pin a CPU core for minutes.\n    price_groups: dict[str, tuple[np.ndarray, np.ndarray]] = {}\n    for code, px in prices.groupby("code", sort=False):\n        ordered = px[["date", "close"]].sort_values("date")\n        price_groups[str(code)] = (\n            ordered["date"].to_numpy(dtype="datetime64[ns]"),\n            ordered["close"].to_numpy(dtype=float),\n        )\n\n    result_parts: list[pd.DataFrame] = []\n    for code, rows in frame.groupby("code", sort=False):\n        price_arrays = price_groups.get(str(code))\n        if price_arrays is None:\n            continue\n        dates, closes = price_arrays\n        g = rows.sort_values("analysis_date").copy()\n        entry = pd.to_numeric(g["close"], errors="coerce").to_numpy(dtype=float)\n        base_dates = g["analysis_date"].to_numpy(dtype="datetime64[ns]")\n        for horizon in HORIZONS:\n            target = base_dates + np.timedelta64(horizon, "D")\n            pos = np.searchsorted(dates, target, side="left")\n            values = np.full(len(g), np.nan, dtype=float)\n            valid = (pos < len(dates)) & np.isfinite(entry) & (entry > 0)\n            if valid.any():\n                values[valid] = closes[pos[valid]] / entry[valid] - 1.0\n            g[f"return_{horizon}d"] = values\n        result_parts.append(g)\n    return pd.concat(result_parts, ignore_index=True, sort=False) if result_parts else pd.DataFrame()\n'''
if text.count(old) != 1:
    raise SystemExit(f"expected exactly one forward-return block, found {text.count(old)}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
